### ISSUE TITLE
docker-entrypoint doesn't detect existing -Xmx setting when applying container settings

### ISSUE THREAD

**Issue by karlvr** [jboss-dockerfiles/infinispan#122]
I think there's a typo in https://github.com/jboss-dockerfiles/infinispan/blob/9.4.x/server/docker-entrypoint.sh and similar on line 307 where it uses `JAVA_OPTIONS` to look for existing `-Xmx` settings.

It's the only mention of `JAVA_OPTIONS` in that file, or in the infinispan-server directory. I think it should be `JAVA_OPTS`.

**Comment by gustavonalle** [comment]
Fixed on master
