### ISSUE TITLE
restarting host-controller doesn't work

### ISSUE THREAD

**Issue by arashbi** [jboss-dockerfiles/infinispan#30]
Entry point shoves username to configuration file. This works fine in the initial start, but afterward, if I want to restart the container, it throws a duplicate attribute exception.

**Comment by slaskawi** [comment]
//cc @gustavonalle

**Comment by gustavonalle** [comment]
@arashbi How can I reproduced it? I tried restarting a host-controller by killing the container and launching it again, and also restarted individual servers via admin console and could not see the exception.

**Comment by arashbi** [comment]
Start the domain-controller : 
```docker run --name dc -itP jboss/infinispan-server:8.2.4.Final domain-controller```
Start the host controller 
```docker run --link dc:dc --name host1 -itP jboss/infinispan-server:8.2.4.Final host-controller````
Stop the host
Start the host again
```docker start host1```
docker logs says : 

> Host Controller] 14:14:19,102 ERROR [org.jboss.as.host.controller] (Controller Boot Thread) WFLYHC0033: Caught exception during boot: org.jboss.as.controller.persistence.ConfigurationPersistenceException: WFLYCTL0085: Failed to parse configuration
[Host Controller] 	at org.jboss.as.controller.persistence.XmlConfigurationPersister.load(XmlConfigurationPersister.java:131)
[Host Controller] 	at org.jboss.as.host.controller.HostControllerConfigurationPersister.load(HostControllerConfigurationPersister.java:188)
[Host Controller] 	at org.jboss.as.host.controller.DomainModelControllerService.boot(DomainModelControllerService.java:577)
[Host Controller] 	at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:299)
[Host Controller] 	at java.lang.Thread.run(Thread.java:745)
[Host Controller] Caused by: com.ctc.wstx.exc.WstxParsingException: Duplicate attribute 'security-realm'.
[Host Controller]  at [row,col {unknown-source}]: [58,83]
[Host Controller] 	at com.ctc.wstx.sr.StreamScanner.constructWfcException(StreamScanner.java:614)
[Host Controller] 	at com.ctc.wstx.sr.StreamScanner.throwParseError(StreamScanner.java:487)
[Host Controller] 	at com.ctc.wstx.sr.StreamScanner.throwParseError(StreamScanner.java:472)
[Host Controller] 	at com.ctc.wstx.sr.AttributeCollector.throwDupAttr(AttributeCollector.java:1162)
[Host Controller] 	at com.ctc.wstx.sr.AttributeCollector.resolveNamespaces(AttributeCollector.java:1016)
[Host Controller] 	at com.ctc.wstx.sr.InputElementStack.resolveAndValidateElement(InputElementStack.java:511)
[Host Controller] 	at com.ctc.wstx.sr.BasicStreamReader.handleStartElem(BasicStreamReader.java:2979)
[Host Controller] 	at com.ctc.wstx.sr.BasicStreamReader.nextFromTree(BasicStreamReader.java:2839)
[Host Controller] 	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1073)
[Host Controller] 	at com.ctc.wstx.sr.BasicStreamReader.nextTag(BasicStreamReader.java:1154)
[Host Controller] 	at org.jboss.staxmapper.XMLExtendedStreamReaderImpl.nextTag(XMLExtendedStreamReaderImpl.java:152)
[Host Controller] 	at org.jboss.as.host.controller.parsing.HostXml_4.parseDomainController(HostXml_4.java:620)
[Host Controller] 	at org.jboss.as.host.controller.parsing.HostXml_4.readHostElement(HostXml_4.java:372)
[Host Controller] 	at org.jboss.as.host.controller.parsing.HostXml_4.readElement(HostXml_4.java:167)
[Host Controller] 	at org.jboss.as.host.controller.parsing.HostXml.readElement(HostXml.java:79)
[Host Controller] 	at org.jboss.as.host.controller.parsing.HostXml.readElement(HostXml.java:50)
[Host Controller] 	at org.jboss.staxmapper.XMLMapperImpl.processNested(XMLMapperImpl.java:110)
[Host Controller] 	at org.jboss.staxmapper.XMLMapperImpl.parseDocument(XMLMapperImpl.java:69)
[Host Controller] 	at org.jboss.as.controller.persistence.XmlConfigurationPersister.load(XmlConfigurationPersister.java:123)
[Host Controller] 	... 4 more

**Comment by gustavonalle** [comment]
#32

**Comment by slaskawi** [comment]
@arashbi Could you please confirm the fix? I'm about to close this issue...
