### ISSUE TITLE
Issue when running the example Docker in domain mode

### ISSUE THREAD

**Issue by AdrienFromToulouse** [jboss-dockerfiles/infinispan#87]
Hi there!

First and foremost, thank you for maintaining Infinispan.

I am currently facing an issue when trying the docker image in domain mode.
I run the following in 2 different tabs:

Tab 1:

```console
docker run -e "MGMT_USER=admin" -e "MGMT_PASS=password" --name=dc -it jboss/infinispan-server domain-controller
```
All good. Everything start properly.

Tab 2:

```console
docker run -e "MGMT_USER=admin" -e "MGMT_PASS=password" --link dc:dc -it jboss/infinispan-server host-controller
```

I get for each of the servers ([Server:server-one] & [Server:server-two]), this error:

<img width="1392" alt="screen shot 2018-04-16 at 13 02 26" src="https://user-images.githubusercontent.com/1558229/38805553-7aca6b12-4176-11e8-8995-2f464b0420bd.png">

Is it because of some additional config that need to be passed to the docker command line?
Is it somehow related to `HotRodServer`?

Thank you in advance for your guidance.

Cheers,

**Comment by gustavonalle** [comment]
This is a [known issue](https://issues.jboss.org/browse/ISPN-9035) that will be fixed on Infinispan 9.2.2.Final, to be released shortly. In the meantime, please use the image ```jboss/infinispan-server:9.2.0.Final```

**Comment by AdrienFromToulouse** [comment]
got it @gustavonalle, many thanks for your reply!

**Comment by gustavonalle** [comment]
9.2.2.Final is available on docker hub, please give it a try
